# Generated by Django 4.0.5 on 2022-12-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0005_articlecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=100, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='菜单名')),
                ('icon', models.CharField(max_length=200, verbose_name='图标字体')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('sort_id', models.CharField(max_length=100, verbose_name='排序')),
                ('status', models.CharField(choices=[('d', '不显示'), ('p', '显示')], default='p', max_length=1, verbose_name='显示')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'menu',
                'ordering': ['status'],
                'get_latest_by': 'status',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='daniuapp_user',
        ),
    ]
