# Generated by Django 4.0.5 on 2022-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0006_menu_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=200, verbose_name='链接地址'),
        ),
    ]
