# Generated by Django 4.0.5 on 2022-12-08 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0007_alter_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_id', models.CharField(max_length=100, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, verbose_name='别名')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('keyword', models.CharField(max_length=200, verbose_name='关键字')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('d', '不显示'), ('p', '显示')], default='p', max_length=1, verbose_name='显示')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面管理',
                'db_table': 'page_management',
                'ordering': ['Page_id'],
                'get_latest_by': 'Page_id',
            },
        ),
    ]
