# Generated by Django 4.0.5 on 2022-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0008_pagemanagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemanagement',
            options={'get_latest_by': 'created_time', 'ordering': ['-created_time'], 'verbose_name': '页面', 'verbose_name_plural': '页面管理'},
        ),
        migrations.RenameField(
            model_name='pagemanagement',
            old_name='Page_id',
            new_name='page_id',
        ),
        migrations.AddField(
            model_name='pagemanagement',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
