# Generated by Django 4.0.5 on 2022-12-08 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0009_alter_pagemanagement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.CharField(max_length=100, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('d', '不显示'), ('p', '显示')], default='p', max_length=1, verbose_name='显示')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
                'db_table': 'notice_management',
                'ordering': ['-created_time'],
                'get_latest_by': 'created_time',
            },
        ),
    ]
