# Generated by Django 4.0.5 on 2022-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniuapp', '0010_noticemanagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '分类名称', 'verbose_name_plural': '分类列表'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='分类名称'),
        ),
    ]
