# Generated by Django 4.0.5 on 2022-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=256, verbose_name='标题')),
                ('contents', models.CharField(max_length=256, verbose_name='内容')),
            ],
        ),
    ]
