# Generated by Django 4.0.5 on 2022-11-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_jiekou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField(default=0)),
                ('c', models.ManyToManyField(to='wx_jiekou.course')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_jiekou.grade')),
            ],
            options={
                'db_table': 'student',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
